import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
    // Deletes ALL existing entries
    await knex("tbl_cust_products2").del();

    // Inserts seed entries
    await knex("tbl_cust_products2").insert([
        {
            id: 1,
            ProdId: 0,
            ProductName: "Ajit Moong Dal",
            BrandId: 0,
            CatId: 5,
            SubCatId: "1",
            CgstPer: "2.5",
            SgstPer: "2.5",
            IgstPer: "0",
            CgstAmt: 0.50,
            SgstAmt: 0.50,
            IgstAmt: 0.00,
            GstAmt: 1.00,
            ProdPrice: 19.00,
            MinPrice: 20.00,
            Status: 1,
            SrNo: 1.00,
            Photo: null,
            code: "jelPOzW35OqQO9S",
            CreatedDate: "2024-12-12 12:52:41",
            ModifiedDate: "2025-01-15 00:00:00",
            CreatedBy: 2091,
            ModifiedBy: 2091,
            BarcodeNo: "8906049251132",
            StockQty: 0,
            TempPrdId: 67913,
            Display: 1,
            push_flag: 0,
            delete_flag: 0,
            modified_time: null,
            ProdType: 0,
            Qty: null,
            Unit: null,
            Transfer: 1,
            Assets: 0,
            QrDisplay: "1",
            MinQty: "50",
            ProdType2: 1,
            PurchasePrice: 9.75,
            checkstatus: 0,
            tempstatus: 0,
          },
          {
            id: 2,
            ProdId: 0,
            ProductName: "Ajit Phalhari Chivda",
            BrandId: 0,
            CatId: 5,
            SubCatId: "1",
            CgstPer: "2.5",
            SgstPer: "2.5",
            IgstPer: "0",
            CgstAmt: 0.50,
            SgstAmt: 0.50,
            IgstAmt: 0.00,
            GstAmt: 1.00,
            ProdPrice: 19.00,
            MinPrice: 20.00,
            Status: 1,
            SrNo: 0.00,
            Photo: null,
            code: "bVU438QSfdf7who",
            CreatedDate: "2024-12-12 12:55:10",
            ModifiedDate: null,
            CreatedBy: 2091,
            ModifiedBy: 0,
            BarcodeNo: "8906049251118",
            StockQty: 0,
            TempPrdId: 0,
            Display: 1,
            push_flag: 0,
            delete_flag: 0,
            modified_time: null,
            ProdType: 0,
            Qty: null,
            Unit: null,
            Transfer: 1,
            Assets: 0,
            QrDisplay: "1",
            MinQty: "50",
            ProdType2: 1,
            PurchasePrice: 9.65,
            checkstatus: 0,
            tempstatus: 0,
          },
          {
            id: 3,
            ProdId: 0,
            ProductName: "Ajit Potato Chips Salted",
            BrandId: 0,
            CatId: 19,
            SubCatId: "0",
            CgstPer: "2.5",
            SgstPer: "2.5",
            IgstPer: "0",
            CgstAmt: 0.50,
            SgstAmt: 0.50,
            IgstAmt: 0.00,
            GstAmt: 1.00,
            ProdPrice: 19.00,
            MinPrice: 20.00,
            Status: 1,
            SrNo: 3.00,
            Photo: null,
            code: "mB0YscqksHadulX",
            CreatedDate: "2024-12-12 13:33:04",
            ModifiedDate: "2025-01-14 20:16:10",
            CreatedBy: 2091,
            ModifiedBy: 2091,
            BarcodeNo: "8906049251149",
            StockQty: 0,
            TempPrdId: 0,
            Display: 1,
            push_flag: 0,
            delete_flag: 0,
            modified_time: null,
            ProdType: 0,
            Qty: null,
            Unit: null,
            Transfer: 1,
            Assets: 0,
            QrDisplay: "1",
            MinQty: "50",
            ProdType2: 1,
            PurchasePrice: 9.59,
            checkstatus: 0,
            tempstatus: 0,
          }
    ]);
};
